### ISSUE TITLE
"No override" vs "Normal" time? 

### ISSUE THREAD

**Issue by Risu64** [Eternita-S/Weatherman#4]
Hello! What's the difference between "No override" and "Normal" time controls? I understand that the latter is "time controlled by plugin" but I don't quite get what's supposed to be different from "No override". Thank you!

**Comment by Eternita-S** [comment]
If you're talking about global time control, there's a little difference in shadow movements - they will move smoother if you select Normal time since plugin updates time a lot faster than game does. Other than this there is no difference really and it's mostly made like this for parity between global and zone-specific control and a bit because of laziness too.

**Comment by Risu64** [comment]
Thank you! Does that mean that "normal" in the zone-specific tab behaves differently from "no override" then?

**Comment by Eternita-S** [comment]
Yeah, if you have global time control set to anything except default/normal, selecting normal for a zone will cause it to display original time. And no override would use global setting.

**Comment by Risu64** [comment]
Ah that makes a lot of sense. Thank you very much!
